export { default as AboutMeComponent } from "./landing/about-me/about-me"
export { default as Photo } from "./landing/about-me/photo"
export { default as ContactMeComponent } from "./landing/contact-me/contact-me"
export { default as MyProjectsComponent } from "./landing/projects/my-projects"
export { default as MyExperienceComponent } from "./landing/work-experience/my-experience"
export { default as Navigation } from "./landing/nav/navigation"
export { default as Projects } from "./landing/projects/my-projects"
export { default as Technologies } from "./landing/tecnologias/my-tecnologias"
export { default as ProjectComponent } from "./projectsPage/projects-component"
export {default as ProcasaExperience} from "./landing/work-experience/procasa-exp"
